### ISSUE TITLE
Cmake issues on ROS2 Dashing

### ISSUE THREAD

**Issue by ruffsl** [christianrauch/raspicam2_node#1]
I'm having some Cmake troubles in building this package on Ubuntu 18.04 with ROS2 Dashing installed via fat archive binaries for arm32v7. I'm able to build the original `raspicam_node` package for ROS1 Melodic just fine on the same environment, so I'm not sure what may be missing.

https://index.ros.org//doc/ros2/Installation/Dashing/Linux-Install-Binary/#downloading-ros-2

```
~/colcon_ws# colcon build
Starting >>> raspicam2
Unsupported ioctl: cmd=0x5441am2 - 0.2s]
Unsupported ioctl: cmd=0x5441
--- stderr: raspicam2                         
CMake Error at /root/ros2_install/ros2-linux/share/class_loader/cmake/class_loader-extras.cmake:3 (find_package):
  Could not find a configuration file for package "poco_vendor" that is
  compatible with requested version "".

  The following configuration files were considered but not accepted:

    /root/ros2_install/ros2-linux/share/poco_vendor/cmake/poco_vendorConfig.cmake, version: 1.1.1 (64bit)

Call Stack (most recent call first):
  /root/ros2_install/ros2-linux/share/class_loader/cmake/class_loaderConfig.cmake:38 (include)
  CMakeLists.txt:9 (find_package)


---
Failed   <<< raspicam2	[ Exited with code 1 ]

Summary: 0 packages finished [6.22s]
  1 package failed: raspicam2
  1 package had stderr output: raspicam2
```

**Comment by christianrauch** [comment]
Although the `raspicam2_node` is a fork of the original ROS1 raspicam node, it's not compatible to ROS1 or it's build system.
From your log, it looks like that `poco_vendor` is missing from your installation, or that is uses the wrong CPU architecture (64bit instead of ARM 32bit).
I've only tested the node with a source build of ROS2 on Raspbian.

Can you build other nodes that require poco in the same workspace?

**Comment by christianrauch** [comment]
Which ROS2 Dashing fat archive did you use?
The release page (https://github.com/ros2/ros2/releases/tag/release-dashing-20190531) only lists `arm64` as the only ARM target architecture. There is no 32bit version for arm.

Are you maybe trying to build with the 64bit ROS2 on a 32bit OS? This might explain why the build system cannot find the corresponding libraries (because it is looking for 32bit poco libs but only finds the 64bit libs from the ROS2 archive).

**Comment by ruffsl** [comment]
> There is no 32bit version for arm.

That's correct. The fat archive I downloaded happened to be mislabeled: https://github.com/ros2/ros2/issues/721

> Are you maybe trying to build with the 64bit ROS2 on a 32bit OS?

I was using QEMU with docker, so probably why the arch mismatch wasn't immediately evident to me.

I'll open a new issue if hit something else, as attempting to use mmal in 64bit seem futile: 
 
https://github.com/raspberrypi/userland/issues/460#issuecomment-382875127
