### ISSUE TITLE
The node is not publishing images

### ISSUE THREAD

**Issue by Veilkrand** [christianrauch/raspicam2_node#12]
The node is not publishing images. But I didn't uninstall these packages:
`sudo apt autoremove --purge libgles2-mesa-dev mesa-common-dev`
It would delete most of the ROS2 Foxy packages...

**Comment by christianrauch** [comment]
Yes, something went wrong with the recent upgrade of the library.

You can try to use an older commit from the history (https://github.com/christianrauch/raspicam2_node/issues/11#issuecomment-699927504) or use the V4L2 driver (https://github.com/christianrauch/raspicam2_node/issues/11#issuecomment-699931002) as a potential workaround.

**Comment by christianrauch** [comment]
I assume the issue you encountered is that you only saw black images published as described in https://github.com/christianrauch/raspicam2_node/issues/11#issuecomment-684085332. This issue was fixed with commit 82603fd and I therefore also assume that this commit fixed your issue too.

I am going to close this issue, assuming it has been resolved by the recent commit that addresses the brightness settings. If you are still seeing missing messages are black images, reopen this issue with more details.
