### ISSUE TITLE
ROS2 Foxy

### ISSUE THREAD

**Issue by russkel** [christianrauch/raspicam2_node#4]
Hi @christianrauch 
Is this project still maintained? I am running ros2 foxy on the new RPiOS 64bit (via docker image) and was wondering if you had any work in the direction of foxy?

**Comment by christianrauch** [comment]
I am not actively using the Raspberry Pi camera at the moment, but I am still going to fix issues with it if they are reported.

Are you facing issues with running the node on ROS2 foxy?

**Comment by russkel** [comment]
I haven't got the stage of running it quite yet. I just noticed it is some commits behind the UbiquityRobotics branch. Do you rebase their work?

I am trying to decide between making a ROS2 port of the UbiquityRobotics repo or roll with your work.

**Comment by christianrauch** [comment]
I initially forked the ROS1 codebase when porting the node to ROS2. These are now two separate codebases since the ROS1 and ROS2 API are different. There is no sensible way to "rebase" the ROS2 code on the ROS1 code.

I tried to establish a common high-level "raspicam" library that both nodes can use (https://github.com/UbiquityRobotics/raspicam_node/issues/73) in order to reuse common functionality. Since the ROS1 node is more widely used, I have to wait until they decide to split the node from the core functionality before relying on this common library.

**Comment by russkel** [comment]
> There is no sensible way to "rebase" the ROS2 code on the ROS1 code.

I didn't mean that in the literal git rebase way, more like porting fixes across.

> I tried to establish a common high-level "raspicam" library that both nodes can use (UbiquityRobotics#73) in order to reuse common functionality.

You have the right idea. It's a shame they didn't run with it.

Thanks for answering the questions, I will attempt to get this running on foxy.

**Comment by christianrauch** [comment]
I will close this as there is nothing to do. You can reopen this issue if you encounter issues on ROS2 foxy.
