### ISSUE TITLE
Parameters are not read from the yaml parameter file on Foxy

### ISSUE THREAD

**Issue by olivier-haddad** [christianrauch/raspicam2_node#9]
The node then always run with the hardcoded defaults.
In order to verify my assumption, I ran "ros2 param dump /camera/raspicam2 --print" and got only:
`use_sim_time: false
`

This happens because the parameters are not declared in the code, so the parameters are simply ignored.

The right way (the one recommended in ros2 documentation) is to declare any parameter used by the node.

An easy/lazy fix is to allow the node to "auto-declare" any parameter that it encounters:
In RasPiCamPublisherNode.cpp, I modified the constructor to:

```
RasPiCamPublisher::RasPiCamPublisher(rclcpp::NodeOptions options)
  : Node("raspicam2", "camera", 
      options
			.use_intra_process_comms(true)
			.allow_undeclared_parameters(true)
			.automatically_declare_parameters_from_overrides(true) )

```
After this modification, "ros2 param dump /camera/raspicam2 --print" prints about 30 parameters.

**Comment by christianrauch** [comment]
> The right way (the one recommended in ros2 documentation) is to declare any parameter used by the node.

Right. I haven't declared the parameters, which is required since `dashing`.

> An easy/lazy fix is to allow the node to "auto-declare" any parameter that it encounters:

I have used `declare_parameter` to declare specific parameters in nodes. I am not sure what the advantage of declaring specific parameters over `allow_undeclared_parameters` and `automatically_declare_parameters_from_overrides` is. I think declaring the parameters makes them appear in the listing while using them undeclared will make them visible only when the node sets them.

I think specifically declaring parameters is the expected use since `dashing`, while the "auto-declare" is for backwards-compatible behaviour. I would therefore prefer to have all parameters explicitly declared via `declare_parameter`. @olivier-haddad Would you mind sending a PR with this?

**Comment by olivier-haddad** [comment]
I think it is not recommended because it would create usability issues.
Allowing auto declaration may create "parameters pollution" and induce users to believe that they rightfully set parameters.
They would see their invalid parameters registered in the node as in a parameter dump even if those are not known at all by the node.
As for the PR, I would have to fix it the right way as I went the lazy way for my tests.
